Namespace(data_path='/scratch/eo41/data/saycam/SAY_5fps_300s_{000000..000009}.tar', vqconfig_path='/scratch/eo41/vqgan-gpt/vqgan_pretrained_models/say_32x32_8192.yaml', vqmodel_path='/scratch/eo41/vqgan-gpt/vqgan_pretrained_models/say_32x32_8192.ckpt', num_workers=8, seed=0, save_dir='/scratch/eo41/vqgan-gpt/gpt_pretrained_models', n_layer=12, n_head=12, n_embd=768, vocab_size=8192, block_size=1023, batch_size=64, print_freq=5000, lr=0.0003, optimizer='Adam', resume='', gpu=None, world_size=-1, rank=-1, dist_url='env://', dist_backend='nccl', local_rank=-1)
Namespace(data_path='/scratch/eo41/data/saycam/SAY_5fps_300s_{000000..000009}.tar', vqconfig_path='/scratch/eo41/vqgan-gpt/vqgan_pretrained_models/say_32x32_8192.yaml', vqmodel_path='/scratch/eo41/vqgan-gpt/vqgan_pretrained_models/say_32x32_8192.ckpt', num_workers=8, seed=0, save_dir='/scratch/eo41/vqgan-gpt/gpt_pretrained_models', n_layer=12, n_head=12, n_embd=768, vocab_size=8192, block_size=1023, batch_size=64, print_freq=5000, lr=0.0003, optimizer='Adam', resume='', gpu=None, world_size=-1, rank=-1, dist_url='env://', dist_backend='nccl', local_rank=-1)
model:
  base_learning_rate: 1.0e-05
  params:
    ddconfig:
      attn_resolutions:
      - 32
      ch: 128
      ch_mult:
      - 1
      - 1
      - 2
      - 4
      double_z: false
      dropout: 0.0
      in_channels: 3
      num_res_blocks: 2
      out_ch: 3
      resolution: 256
      z_channels: 256
    embed_dim: 256
    lossconfig:
      params:
        codebook_weight: 1.0
        disc_conditional: false
        disc_in_channels: 3
        disc_start: 100001
        disc_weight: 0.2
      target: vqloss.VQLPIPSWithDiscriminator
    n_embed: 8192
  target: vqmodel.VQModel

Working with z of shape (1, 256, 32, 32) = 262144 dimensions.
loaded pretrained LPIPS loss from taming/modules/autoencoder/lpips/vgg.pth
VQLPIPSWithDiscriminator running with hinge loss.
Running on 2 GPUs total
Number of parameters: 98424576
=> no checkpoint loaded, will train from scratch
Traceback (most recent call last):
  File "/scratch/eo41/vqgan-gpt/train.py", line 115, in <module>
    _, loss, _ = model(indices[:, :-1], indices[:, 1:])  # first output returns logits, last one returns unreduced losses
  File "/scratch/eo41/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/scratch/eo41/miniconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 886, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/scratch/eo41/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/scratch/eo41/vqgan-gpt/gptmodel.py", line 151, in forward
Traceback (most recent call last):
  File "/scratch/eo41/vqgan-gpt/train.py", line 115, in <module>
    _, loss, _ = model(indices[:, :-1], indices[:, 1:])  # first output returns logits, last one returns unreduced losses
  File "/scratch/eo41/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/scratch/eo41/miniconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 886, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/scratch/eo41/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/scratch/eo41/vqgan-gpt/gptmodel.py", line 151, in forward
    x = self.blocks(x)
  File "/scratch/eo41/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    x = self.blocks(x)
  File "/scratch/eo41/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/scratch/eo41/miniconda3/lib/python3.9/site-packages/torch/nn/modules/container.py", line 141, in forward
    return forward_call(*input, **kwargs)
  File "/scratch/eo41/miniconda3/lib/python3.9/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/scratch/eo41/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    input = module(input)
  File "/scratch/eo41/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
    return forward_call(*input, **kwargs)
  File "/scratch/eo41/vqgan-gpt/gptmodel.py", line 103, in forward
  File "/scratch/eo41/vqgan-gpt/gptmodel.py", line 103, in forward
    x = x + self.attn(self.ln1(x))
    x = x + self.attn(self.ln1(x))
  File "/scratch/eo41/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
  File "/scratch/eo41/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/scratch/eo41/vqgan-gpt/gptmodel.py", line 76, in forward
    return forward_call(*input, **kwargs)
  File "/scratch/eo41/vqgan-gpt/gptmodel.py", line 76, in forward
    att = (q @ k.transpose(-2, -1)) * (1.0 / math.sqrt(k.size(-1)))
    att = (q @ k.transpose(-2, -1)) * (1.0 / math.sqrt(k.size(-1)))
RuntimeError: CUDA out of memory. Tried to allocate 3.00 GiB (GPU 1; 79.17 GiB total capacity; 74.56 GiB already allocated; 1.01 GiB free; 75.84 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
RuntimeError: CUDA out of memory. Tried to allocate 3.00 GiB (GPU 0; 79.17 GiB total capacity; 74.56 GiB already allocated; 1.04 GiB free; 75.81 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
srun: error: ga004: task 0: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=24532291.0
slurmstepd: error: *** STEP 24532291.0 ON ga004 CANCELLED AT 2022-09-06T16:04:21 ***
srun: error: ga004: task 1: Exited with exit code 1
Done
